---
# tasks file for kibana
- name: Download Kibana
  get_url:
    url: "{{kibana_download_url}}"
    dest: /tmp

- name: Install Kibana
  yum: 
    name: "/tmp/{{kibana_yum_package_name }}"
    state: present

- name: Update Kibana config
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify: restart kibana
