---
# tasks file for fluentd
- name: Download td-agent install script
  get_url:
    url: https://toolbelt.treasuredata.com/sh/install-redhat-td-agent3.sh
    dest: /tmp/install-redhat-td-agent3.sh
    mode: u+x

- name: Install td-agent
  command: /bin/bash /tmp/install-redhat-td-agent3.sh
  notify: restart fluentd

- name: Install gem needed for elasticsearch 
  command: /opt/td-agent/embedded/bin/gem install fluent-plugin-elasticsearch --no-rdoc --no-ri --version 1.9.2

- name: write our td-agent.conf
  template: src=fluentd.conf.j2 dest=/etc/td-agent/td-agent.conf
  notify: restart fluentd

