---
# tasks file for elasticsearch
- name: Install which for elasticsearch init.d file
  package:
    name: which
    state: latest

- name: Download Elasticsearch
  get_url:
    url: "{{ elasticsearch_download_url }}"
    dest: /tmp

- name: Install Elasticsearch
  yum: 
    name: "/tmp/{{elasticsearch_yum_package_name }}"
    state: present

- name: Create needed directories with correct structure
  file:
    path: "{{item}}"
    owner: elasticsearch
    group: elasticsearch
    mode: 0750
    recurse: yes
    state: directory
  with_items: ["/usr/share/elasticsearch","/data"]
  notify: restart elasticsearch

- name: Configuring Elasticsearch Defaults
  template:
    src: elasticsearch.j2
    dest: /etc/default/elasticsearch
    owner: root
    group: root
    mode: 0644
  notify: restart elasticsearch

- name: Configuring JVM Elasticsearch
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
    owner: root
    group: elasticsearch
    mode: 0644
  notify: restart elasticsearch

- name: Configuring Logging Elasticsearch
  template:
    src: log4j2.properties.j2
    dest: /etc/elasticsearch/log4j2.properties
    owner: root
    group: elasticsearch
    mode: 0644
  notify: restart elasticsearch

- name: Configuring Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0644
  notify: restart elasticsearch

- name: Make sure elasticsearch is running
  service:
    name: elasticsearch
    state: started
    enabled: yes
