---
# tasks file for java
- name: Download jdk file for installation
  get_url:
    headers: "Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
    url: "{{java_download_url}}"
    dest: "/tmp/{{java_rpm_package_name}}"
    validate_certs: "no"
    timeout: 600

- name: Install jdk rpm
  yum: 
    name: "/tmp/{{java_rpm_package_name}}"
    state: present

- name: set Java version as default
  alternatives:
    name: "{{ item.exe }}"
    link: "/usr/bin/{{ item.exe }}"
    path: "{{ item.path }}/{{item.exe}}"
  with_items:
    - { path: "{{ java_home }}/jre/bin", exe: "java" }
    - { path: "{{ java_home }}/jre/bin", exe: "keytool" }
    - { path: "{{ java_home }}/bin", exe: "javac" }
    - { path: "{{ java_home }}/bin", exe: "javadoc" }
