version: "2"
  
services:
  fluentd:
    build: 
      context: ./env
      dockerfile: Dockerfile-fluentd
    hostname: fluentd
    logging:
      driver: "fluentd"
      options:
        tag: fluentd.logs
  control:
    build: 
      context: ./env
      dockerfile: Dockerfile-control
    hostname: control
    links:
      - lb
      - web1
      - web2
      - fluentd
      - elasticsearch
      - kibana
    depends_on:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        tag: control.logs
  lb:
    build: 
      context: ./env
      dockerfile: Dockerfile-general
    hostname: lb
    links:
      - web1
      - web2
      - fluentd
    depends_on:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        tag: lb.logs
  web1:
    build: 
      context: ./env
      dockerfile: Dockerfile-general
    hostname: web1
    links:
      - fluentd
    depends_on:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        tag: web1.logs
  web2:
    build: 
      context: ./env
      dockerfile: Dockerfile-general
    hostname: web2
    links:
      - fluentd
    depends_on:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        tag: web2.logs
  elasticsearch:
    build: 
      context: ./env
      dockerfile: Dockerfile-general
    hostname: elasticsearch
    depends_on:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        tag: elasticsearch.logs
  kibana:
    build: 
      context: ./env
      dockerfile: Dockerfile-general
    hostname: kibana
    links:
      - elasticsearch
    depends_on:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        tag: kibana.logs
