FROM ubuntu:xenial

RUN apt-get update && apt-get install -y curl openssh-server gnupg2  && \
  gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 && \
  curl -L https://get.rvm.io |bash -s stable --ruby 

RUN curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-xenial-td-agent3.sh | sh && \
  useradd ansible -s /bin/bash && \
  mkdir -p /home/ansible/.ssh/ && \
  chmod 0700 /home/ansible/.ssh/

RUN sed -i 's/prohibit-password/yes/' /etc/ssh/sshd_config

RUN echo "StrictHostKeyChecking=no" >> /etc/ssh/ssh_config

COPY ssh_config /home/ansible/.ssh/config
COPY ansible /home/ansible/.ssh/id_rsa
COPY ansible.pub /home/ansible/.ssh/id_rsa.pub
COPY ansible.pub /home/ansible/.ssh/authorized_keys

RUN chown -R ansible:ansible /home/ansible/ && \
  echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-rdoc", "--no-ri", "--version", "1.9.2"]

ENV container docker

EXPOSE 22
CMD ["/usr/sbin/service", "sshd", "restart"]
CMD ["/etc/init.d/td-agent", "restart"]
